---
name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # cache pip dependencies
    - run: sudo apt-get install -y libegl-mesa0
    - run: pip install -r requirements.txt
    - run: pip --version
    - run: python lw_report_gen.py --author Author --customer Customer
      env:
        LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
        LW_SUBACCOUNT: ${{ secrets.LW_SUBACCOUNT }}
        LW_API_KEY: ${{ secrets.LW_API_KEY }}
        LW_API_SECRET: ${{ secrets.LW_API_SECRET }}
        LOGLEVEL: WARNING
